
This dataset comes from data.gov:  
https://catalog.data.gov/dataset/crime-data-from-2020-to-present

In [69]:
import pandas as pd
import numpy as np

In [ ]:
#Original Dataset
file_path = "/Users/kamari/Documents/project_info/Crime_Data_from_2020_to_2024.csv"
df = pd.read_csv(file_path)
df

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,211507896,04/11/2021 12:00:00 AM,11/07/2020 12:00:00 AM,845,15,N Hollywood,1502,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,7800 BEEMAN AV,NaN,34.2124,-118.4092
1,201516622,10/21/2020 12:00:00 AM,10/18/2020 12:00:00 AM,1845,15,N Hollywood,1521,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",...,IC,Invest Cont,230.0,NaN,NaN,NaN,ATOLL AV,N GAULT,34.1993,-118.4203
2,240913563,12/10/2024 12:00:00 AM,10/30/2020 12:00:00 AM,1240,9,Van Nuys,933,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,14600 SYLVAN ST,NaN,34.1847,-118.4509
3,210704711,12/24/2020 12:00:00 AM,12/24/2020 12:00:00 AM,1310,7,Wilshire,782,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,...,IC,Invest Cont,331.0,NaN,NaN,NaN,6000 COMEY AV,NaN,34.0339,-118.3747
4,201418201,10/03/2020 12:00:00 AM,09/29/2020 12:00:00 AM,1830,14,Pacific,1454,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),...,IC,Invest Cont,420.0,NaN,NaN,NaN,4700 LA VILLA MARINA,NaN,33.9813,-118.4350
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1004889,240710284,07/24/2024 12:00:00 AM,07/23/2024 12:00:00 AM,1400,7,Wilshire,788,1,510,VEHICLE - STOLEN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,4000 W 23RD ST,NaN,34.0362,-118.3284
1004890,240104953,01/15/2024 12:00:00 AM,01/15/2024 12:00:00 AM,100,1,Central,101,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,IC,Invest Cont,745.0,NaN,NaN,NaN,1300 W SUNSET BL,NaN,34.0685,-118.2460
1004891,240410786,10/14/2024 12:00:00 AM,10/11/2024 12:00:00 AM,2330,4,Hollenbeck,421,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",...,IC,Invest Cont,341.0,NaN,NaN,NaN,1700 ALBION ST,NaN,34.0675,-118.2240
1004892,240309674,04/24/2024 12:00:00 AM,04/24/2024 12:00:00 AM,1500,3,Southwest,358,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",...,IC,Invest Cont,230.0,NaN,NaN,NaN,FLOWER ST,JEFFERSON BL,34.0215,-118.2868
1004893,240910892,08/13/2024 12:00:00 AM,08/12/2024 12:00:00 AM,2300,9,Van Nuys,914,1,510,VEHICLE - STOLEN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,6900 VESPER AV,NaN,34.1961,-118.4510

### Data Cleaning Notes
remove Cross Street  
- not helpful info  
- almost 1 million empty values  

remove Mocodes and Premis Cd  
- not human readable (needs lookup table)  
- crime code + description already give details (no nulls)  
- lots of missing values  

remove Rpt Dist No  
- same issue as mocodes  
- will use AREA, AREA name, lat, lon instead  

renamed columns
- Changed the titles for multiple columns to increase clarity

standardize Vict Sex  
- Male  
- Female  
- Unspecified  

cleaned Vict Descent
- Replaced placeholder values ('-', 'X') with missing
- Converted coded values (e.g., 'H', 'W') to descriptive labels
- e.g., 'H: Hispanic/Latino', 'W: White'
- Filled missing values as Unspecified

cleaned Vict Age
- Converted column to numeric type
- Replaced fake values ≤ 0 with missing (NaN)
- Verified valid ages remained unchanged after cleaning

cleaned Date Rptd and DATE OCC
- Converted from string format to datetime
- Standardized format to YYYY-MM-DD
- Removed unnecessary time component (12:00:00 AM)
- Verified dates remained unchanged after conversion

cleaned TIME OCC
- Converted HHMM integer format to standard time format (HH:MM:SS)
- Verified hour and minute components match original values

In [21]:
clean_df = df.drop(columns=['Cross Street', 'Mocodes','Premis Cd','Rpt Dist No'])
clean_df

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Part 1-2,Crm Cd,Crm Cd Desc,Vict Age,...,Weapon Desc,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,LAT,LON
0,211507896,04/11/2021 12:00:00 AM,11/07/2020 12:00:00 AM,845,15,N Hollywood,2,354,THEFT OF IDENTITY,31,...,NaN,IC,Invest Cont,354.0,NaN,NaN,NaN,7800 BEEMAN AV,34.2124,-118.4092
1,201516622,10/21/2020 12:00:00 AM,10/18/2020 12:00:00 AM,1845,15,N Hollywood,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",32,...,KNIFE WITH BLADE 6INCHES OR LESS,IC,Invest Cont,230.0,NaN,NaN,NaN,ATOLL AV,34.1993,-118.4203
2,240913563,12/10/2024 12:00:00 AM,10/30/2020 12:00:00 AM,1240,9,Van Nuys,2,354,THEFT OF IDENTITY,30,...,NaN,IC,Invest Cont,354.0,NaN,NaN,NaN,14600 SYLVAN ST,34.1847,-118.4509
3,210704711,12/24/2020 12:00:00 AM,12/24/2020 12:00:00 AM,1310,7,Wilshire,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,47,...,NaN,IC,Invest Cont,331.0,NaN,NaN,NaN,6000 COMEY AV,34.0339,-118.3747
4,201418201,10/03/2020 12:00:00 AM,09/29/2020 12:00:00 AM,1830,14,Pacific,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),63,...,NaN,IC,Invest Cont,420.0,NaN,NaN,NaN,4700 LA VILLA MARINA,33.9813,-118.4350
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1004889,240710284,07/24/2024 12:00:00 AM,07/23/2024 12:00:00 AM,1400,7,Wilshire,1,510,VEHICLE - STOLEN,0,...,NaN,IC,Invest Cont,510.0,NaN,NaN,NaN,4000 W 23RD ST,34.0362,-118.3284
1004890,240104953,01/15/2024 12:00:00 AM,01/15/2024 12:00:00 AM,100,1,Central,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),0,...,UNKNOWN WEAPON/OTHER WEAPON,IC,Invest Cont,745.0,NaN,NaN,NaN,1300 W SUNSET BL,34.0685,-118.2460
1004891,240410786,10/14/2024 12:00:00 AM,10/11/2024 12:00:00 AM,2330,4,Hollenbeck,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",29,...,NaN,IC,Invest Cont,341.0,NaN,NaN,NaN,1700 ALBION ST,34.0675,-118.2240
1004892,240309674,04/24/2024 12:00:00 AM,04/24/2024 12:00:00 AM,1500,3,Southwest,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",70,...,STICK,IC,Invest Cont,230.0,NaN,NaN,NaN,FLOWER ST,34.0215,-118.2868
1004893,240910892,08/13/2024 12:00:00 AM,08/12/2024 12:00:00 AM,2300,9,Van Nuys,1,510,VEHICLE - STOLEN,0,...,NaN,IC,Invest Cont,510.0,NaN,NaN,NaN,6900 VESPER AV,34.1961,-118.4510

In [ ]:
# standardize 'Vict Sex' column to have consistent values: 'Male ', 'Female ', and 'Unspecified'
clean_df['Vict Sex'] = clean_df['Vict Sex'].apply(lambda x: 'Unspecified' if x != 'F' and x != 'M' else x)
clean_df.loc[clean_df['Vict Sex'] == 'M', 'Vict Sex'] = 'Male'
clean_df.loc[clean_df['Vict Sex'] == 'F', 'Vict Sex'] = 'Female'

In [89]:
df['Vict Descent'].unique()

<StringArray>
['H', 'W', 'A', 'B', nan, 'X', 'O', 'C', 'J', 'V', 'K', 'F', 'I', 'Z', 'L',
 'G', 'P', 'D', 'U', 'S', '-']
Length: 21, dtype: str

In [97]:

clean_df['Vict Descent'] = (
    clean_df['Vict Descent']
    .astype(str)      # convert everything to string
    .str.strip()      # remove leading/trailing whitespace
    .str.upper()      # make all text uppercase
)
# replace any value that is not a valid descent code with NaN
clean_df['Vict Descent'] = clean_df['Vict Descent'].replace('-', np.nan)
clean_df['Vict Descent'] = clean_df['Vict Descent'].replace(['-', 'X'], np.nan)

In [ ]:
descent_map = {
    'H': 'H: Hispanic/Latino',
    'W': 'W: White',
    'B': 'B: Black',
    'A': 'A: Other Asian',
    'C': 'C: Chinese',
    'J': 'J: Japanese',
    'K': 'K: Korean',
    'F': 'F: Filipino',
    'V': 'V: Vietnamese',
    'I': 'I: American Indian/Alaska Native',
    'P': 'P: Pacific Islander',
    'O': 'O: Other',
    'Z': 'Z: Asian Indian',
    'G': 'G: Guamanian',
    'U': 'U: Hawaiian',
    'D': 'D: Cambodian',
    'L': 'L: Laotian',
    'S': 'S: Samoan'
}
# replace '-' and 'X' with NaN then map the remaining values to their full descriptions, filling with 'Unspecified'
clean_df['Vict Descent'] = clean_df['Vict Descent'].map(descent_map).fillna('Unspecified')

In [99]:
clean_df['Vict Descent'].unique()

<StringArray>
[              'H: Hispanic/Latino',                         'W: White',
                   'A: Other Asian',                         'B: Black',
                      'Unspecified',                         'O: Other',
                       'C: Chinese',                      'J: Japanese',
                    'V: Vietnamese',                        'K: Korean',
                      'F: Filipino', 'I: American Indian/Alaska Native',
                  'Z: Asian Indian',                       'L: Laotian',
                     'G: Guamanian',              'P: Pacific Islander',
                     'D: Cambodian',                      'U: Hawaiian',
                        'S: Samoan']
Length: 19, dtype: str

In [100]:
df['Vict Descent'].value_counts()

Vict Descent
H    296370
W    201429
B    135809
X    106661
O     78001
A     21338
K      5990
F      4838
C      4631
J      1586
V      1195
I      1015
Z       577
P       288
U       221
D        91
L        77
G        74
S        58
-         2
Name: count, dtype: int64

In [101]:
clean_df['Vict Descent'].value_counts()

Vict Descent
H: Hispanic/Latino                  296370
Unspecified                         251306
W: White                            201429
B: Black                            135809
O: Other                             78001
A: Other Asian                       21338
K: Korean                             5990
F: Filipino                           4838
C: Chinese                            4631
J: Japanese                           1586
V: Vietnamese                         1195
I: American Indian/Alaska Native      1015
Z: Asian Indian                        577
P: Pacific Islander                    288
U: Hawaiian                            221
D: Cambodian                            91
L: Laotian                              77
G: Guamanian                            74
S: Samoan                               58
Name: count, dtype: int64

In [104]:
clean_df['Vict Age'].describe()

count    1.004894e+06
mean     2.891862e+01
std      2.199267e+01
min     -4.000000e+00
25%      0.000000e+00
50%      3.000000e+01
75%      4.400000e+01
max      1.200000e+02
Name: Vict Age, dtype: float64

In [ ]:
# remove impossible 0 and negative ages replace with NaN
clean_df.loc[clean_df['Vict Age'] <= 0, 'Vict Age'] = np.nan

In [122]:
clean_df[clean_df['Vict Age'] > 100]

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Part 1-2,Crm Cd,Crm Cd Desc,Vict Age,...,Weapon Desc,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,LAT,LON
198292,200808494,04/19/2020 12:00:00 AM,04/19/2020 12:00:00 AM,2145,8,West LA,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",120.0,...,SEMI-AUTOMATIC PISTOL,IC,Invest Cont,230.0,998.0,NaN,NaN,2000 S BEDFORD ST,34.0416,-118.3836

In [116]:
clean_df['Vict Age'].describe()

count    735579.000000
mean         39.506748
std          15.570937
min           2.000000
25%          28.000000
50%          37.000000
75%          50.000000
max         120.000000
Name: Vict Age, dtype: float64

In [124]:
# convert to datetime
clean_df['Date Rptd'] = pd.to_datetime(clean_df['Date Rptd'], errors='coerce')
clean_df['DATE OCC'] = pd.to_datetime(clean_df['DATE OCC'], errors='coerce')

/var/folders/mn/9tgh57td59q1bnz60jbjnhz00000gn/T/ipykernel_53348/567366880.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  clean_df['Date Rptd'] = pd.to_datetime(clean_df['Date Rptd'], errors='coerce')
/var/folders/mn/9tgh57td59q1bnz60jbjnhz00000gn/T/ipykernel_53348/567366880.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  clean_df['DATE OCC'] = pd.to_datetime(clean_df['DATE OCC'], errors='coerce')

In [134]:
clean_df[['Date Rptd', 'DATE OCC']]

         Date Rptd   DATE OCC
0       2021-04-11 2020-11-07
1       2020-10-21 2020-10-18
2       2024-12-10 2020-10-30
3       2020-12-24 2020-12-24
4       2020-10-03 2020-09-29
...            ...        ...
1004889 2024-07-24 2024-07-23
1004890 2024-01-15 2024-01-15
1004891 2024-10-14 2024-10-11
1004892 2024-04-24 2024-04-24
1004893 2024-08-13 2024-08-12

[1004894 rows x 2 columns]

In [ ]:
(clean_df['TIME OCC'] <= 2359).all()

np.True_

In [ ]:
clean_df['TIME OCC'] = (
    pd.to_datetime(
        clean_df['TIME OCC']
        .astype(str)      # convert integers to strings
        .str.zfill(4),     # pad with leading zeros : 100 → 0100
        format='%H%M',     # specify HHMM time format
        errors='coerce'    # invalid values NaT
    )
    .dt.time              # extract time 
)

In [151]:
clean_df[['TIME OCC']]

         TIME OCC
0        08:45:00
1        18:45:00
2        12:40:00
3        13:10:00
4        18:30:00
...           ...
1004889  14:00:00
1004890  01:00:00
1004891  23:30:00
1004892  15:00:00
1004893  23:00:00

[1004894 rows x 1 columns]

In [ ]:
# rename some columns for clarity
clean_df.rename(columns={
    'Date Rptd': 'Date Reported',
    'DATE OCC': 'Date Occurred',
    'TIME OCC': 'Time Occurred',
    'Crm Cd': 'Crime Code' , 
    'Part 1-2': 'UCR Part Classification',
    'Crm Cd Desc': 'Crime Description',
    'Vict Age': 'Victim Age',
    'Vict Sex': 'Victim Sex',
    'Vict Descent': 'Victim Ethnicity',
    'Premis Desc': 'Premise Description',
    'Weapon Used Cd': 'Weapon Code',
    'Weapon Desc': 'Weapon Description',
    'Crm Cd 1': 'Crime Code 1',
    'Crm Cd 2': 'Crime Code 2',
    'Crm Cd 3': 'Crime Code 3',
    'Crm Cd 4': 'Crime Code 4',
}, inplace=True)

In [166]:
clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1004894 entries, 0 to 1004893
Data columns (total 24 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   DR_NO                    1004894 non-null  int64
 1   Date Reported            1004894 non-null  datetime64[us]
 2   Date Occurred            1004894 non-null  datetime64[us]
 3   Time Occurred            1004894 non-null  object
 4   AREA                     1004894 non-null  int64
 5   AREA NAME                1004894 non-null  str
 6   UCR Part Classification  1004894 non-null  int64
 7   Crime Code               1004894 non-null  int64
 8   Crime Description        1004894 non-null  str
 9   Victim Age               735579 non-null   float64
 10  Victim Sex               1004894 non-null  str
 11  Victim Ethnicity         1004894 non-null  str
 12  Premise Description      1004306 non-null  str
 13  Weapon Code              327216 non-null   float64
 14  Weapon Description       327216 non-null   str
 15  Status                   1004893 non-null  str
 16  Status Desc              1004894 non-null  str
 17  Crime Code 1             1004883 non-null  float64
 18  Crime Code 2             69154 non-null    float64
 19  Crime Code 3             2314 non-null     float64
 20  Crime Code 4             64 non-null       float64
 21  LOCATION                 1004894 non-null  str
 22  LAT                      1004894 non-null  float64
 23  LON                      1004894 non-null  float64
dtypes: datetime64[us](2), float64(8), int64(4), object(1), str(9)
memory usage: 184.0+ MB

## Victim Demographics

Counts and percentages were calculated to examine the distribution of victims across key demographic groups.

- Victim Age: Identifies which age groups are most frequently affected
- Victim Sex: Shows differences in victimization by gender
- Victim Ethnicity: Highlights how crime is distributed across demographic groups

In [167]:
clean_df['Victim Age'].value_counts()

# calculate the percentage of each category
clean_df['Victim Age'].value_counts(normalize=True) * 100

Victim Age
30.0     3.029994
35.0     2.968002
31.0     2.911856
29.0     2.901524
28.0     2.850680
           ...
95.0     0.013595
96.0     0.012779
97.0     0.009788
98.0     0.009652
120.0    0.000136
Name: proportion, Length: 99, dtype: float64

In [168]:
clean_df['Victim Sex'].value_counts()

# calculate the percentage of each category
clean_df['Victim Sex'].value_counts(normalize=True) * 100

Victim Sex
Male           40.187522
Female         35.680679
Unspecified    24.131799
Name: proportion, dtype: float64

In [202]:
clean_df['Victim Ethnicity'].value_counts()

# calculate the percentage of each category
clean_df['Victim Ethnicity'].value_counts(normalize=True) * 100

Victim Ethnicity
H: Hispanic/Latino                  29.492663
Unspecified                         25.008210
W: White                            20.044801
B: Black                            13.514759
O: Other                             7.762112
A: Other Asian                       2.123408
K: Korean                            0.596083
F: Filipino                          0.481444
C: Chinese                           0.460845
J: Japanese                          0.157828
V: Vietnamese                        0.118918
I: American Indian/Alaska Native     0.101006
Z: Asian Indian                      0.057419
P: Pacific Islander                  0.028660
U: Hawaiian                          0.021992
D: Cambodian                         0.009056
L: Laotian                           0.007662
G: Guamanian                         0.007364
S: Samoan                            0.005772
Name: proportion, dtype: float64

## Analytical Functions

Custom functions created to extract key patterns from the dataset. They allow for reusable analysis and make it easier to explore relationships between time, location, and crime type.

- Top Crimes: Identifies the most frequent crime types based on code and description
- Top Locations: Determines which areas experience the highest number of crimes
- Crimes by Month: Highlights seasonal patterns in crime 
- Crimes by Hour: Examines how crime frequency can change in 1 day

In [ ]:
# function to get the most common crimes by their codes and descriptions
def get_top_crimes(df, top_n=10):
    return (df[['Crime Code', 'Crime Description']]  # select crime code and description
        .drop_duplicates()  # keep one row per crime code to drop duplicates
        .merge(
            df['Crime Code'].value_counts().rename('Count'),  # count number of instances per crime code
            left_on='Crime Code',
            right_index=True
        )
        .sort_values(by='Count', ascending=False)  # sort crimes by highest frequency
        .head(top_n)  # keep top N crimes
        .reset_index(drop=True) 
    )
    
get_top_crimes(clean_df)

   Crime Code                                  Crime Description   Count
0         510                                   VEHICLE - STOLEN  115184
1         624                           BATTERY - SIMPLE ASSAULT   74821
2         330                              BURGLARY FROM VEHICLE   63515
3         354                                  THEFT OF IDENTITY   62536
4         740  VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...   61086
5         310                                           BURGLARY   57871
6         440                 THEFT PLAIN - PETTY ($950 & UNDER)   53716
7         230     ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT   53523
8         626                  INTIMATE PARTNER - SIMPLE ASSAULT   46712
9         420    THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER)   41311

In [ ]:
# function to get the most common area crimes happen by their codes and names
def get_top_crime_locations(df, top_n=10):
    return (df[['AREA', 'AREA NAME']]  # select area code and area name
        .drop_duplicates()  # keep one row per AREA to avoid duplicates
        .merge(
            df['AREA'].value_counts().rename('Count'),  # count number of crimes per AREA
            left_on='AREA',
            right_index=True
        )
        .sort_values(by='Count', ascending=False)  # sort areas by highest crime count
        .head(top_n)  # keep top N areas
        .reset_index(drop=True)  
    )
    
get_top_crime_locations(clean_df)

   AREA    AREA NAME  Count
0     1      Central  69668
1    12  77th Street  61756
2    14      Pacific  59513
3     3    Southwest  57434
4     6    Hollywood  52429
5    15  N Hollywood  51106
6    20      Olympic  50070
7    18    Southeast  49929
8    13       Newton  49173
9     7     Wilshire  48237

In [ ]:
def get_crimes_by_month_name(df):
    return (
        df.groupby(df['Date Occurred'].dt.month_name())  # group by month name from Date Occurred
        .size()  # count number of crimes per month
        .reindex(['January', 'February', 'March', 'April', 'May', 'June',
            'July', 'August', 'September', 'October', 'November', 'December'
        ])  # reorder months into correct order
        .reset_index(name='Count')  # convert into DataFrame with Count column
        .rename(columns={'Date Occurred': 'Month'})  # rename column 
    )

get_crimes_by_month_name(clean_df)

        Month  Count
0     January  92675
1    February  86357
2       March  87794
3       April  83517
4         May  83011
5        June  81382
6        July  83962
7      August  83850
8   September  81015
9     October  84127
10   November  78978
11   December  78226

In [ ]:
# function to get number of crimes per hour sorted by frequency
def get_crimes_by_hour(df):
    return (
        df.groupby(pd.to_datetime(df['Time Occurred'].astype(str)).dt.hour)  # group by hour
        .size()  # count crimes per hour
        .reset_index(name='Count')  # convert to DataFrame with Count column
        .rename(columns={'Time Occurred': 'Hour'})  # rename column
        .sort_values(by='Count', ascending=False)  # sort by highest count
        .reset_index(drop=True)  
    )

get_crimes_by_hour(clean_df)

/var/folders/mn/9tgh57td59q1bnz60jbjnhz00000gn/T/ipykernel_53348/293624047.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df.groupby(pd.to_datetime(df['Time Occurred'].astype(str)).dt.hour)  # group by hour

    Hour  Count
0     12  67806
1     18  59955
2     17  58809
3     20  56349
4     19  55596
5     16  52968
6     15  52811
7     21  50788
8     14  49295
9     22  49100
10    13  45572
11    11  43663
12    10  43020
13    23  42277
14     0  40467
15     8  37243
16     9  36519
17     1  29760
18     7  26264
19     2  25214
20     6  23184
21     3  22190
22     4  18756
23     5  17288

## Crime Timing Patterns

- This analysis explores whether certain crimes peak at any specific times of day.

Conclusion: 
- Vehicle theft makes up the majority of crimes, with most of them happening at night, 6 pm being the peak, but reports continue throughout the night at around a similar level of occurrence. The interesting outliers were identity theft, which mostly occurred at around noon and midnight, with the noon occurrences being the single most reported crime in the dataset. The increase in car theft at night speaks for itself, but the identity theft discovery led me to some research where I learned that because noon is when many people are often distracted by work and lunch hours, this is a peak time for the use of public Wi-Fi or ATMs, which increases vulnerability to scams and card skimming. At midnight, online activity shifts to more automated processes, so criminals try to take advantage of this and use bots to test stolen credentials, run phishing attempts, and make unauthorized transactions while victims are less likely to notice.

In [ ]:

# function to get number of crimes by hour and crime type
def crime_by_hour(df, top_n=10):
    return (
        df.groupby([
            pd.to_datetime(df['Time Occurred'].astype(str)).dt.hour,  # convert and extract hour
            'Crime Description'
        ])
        .size()  # count occurrences
        .reset_index(name='Count')  # convert to DataFrame
        .sort_values(by='Count', ascending=False)  # sort by highest frequency
        .head(top_n)  # keep top N combinations
        .reset_index(drop=True)  # clean index
    )
    
crime_by_hour(clean_df)

/var/folders/mn/9tgh57td59q1bnz60jbjnhz00000gn/T/ipykernel_53348/2551588580.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(df['Time Occurred'].astype(str)).dt.hour,  # convert + extract hour

   Time Occurred  Crime Description  Count
0             12  THEFT OF IDENTITY  10381
1             18   VEHICLE - STOLEN   8708
2             20   VEHICLE - STOLEN   8516
3             22   VEHICLE - STOLEN   8243
4             19   VEHICLE - STOLEN   8153
5             21   VEHICLE - STOLEN   7944
6             17   VEHICLE - STOLEN   7470
7             23   VEHICLE - STOLEN   6480
8              0  THEFT OF IDENTITY   6158
9             16   VEHICLE - STOLEN   5752

In [ ]:
# function to get number of crimes by month and crime type
def crime_by_month(df, top_n=10):
    return (
        df.groupby([
            pd.to_datetime(df['Date Occurred'].astype(str)).dt.month,  # convert and extract month
            'Crime Description'
        ])
        .size()  # count occurrences
        .reset_index(name='Count')  # convert to DataFrame
        .sort_values(by='Count', ascending=False)  # sort by highest frequency
        .head(top_n)  # keep top N combinations
        .reset_index(drop=True)  # clean index
    )
    
crime_by_month(clean_df)

   Date Occurred Crime Description  Count
0             10  VEHICLE - STOLEN  10311
1              7  VEHICLE - STOLEN  10121
2              8  VEHICLE - STOLEN  10038
3              5  VEHICLE - STOLEN   9755
4             11  VEHICLE - STOLEN   9742
5              6  VEHICLE - STOLEN   9704
6              9  VEHICLE - STOLEN   9635
7              1  VEHICLE - STOLEN   9476
8              4  VEHICLE - STOLEN   9472
9              3  VEHICLE - STOLEN   9358

## Crime Reporting Delays

- This analysis examines how long it takes for crimes to be reported after they occur. A report delay variable was created by calculating the difference between the date reported and the date occurred.
- This allows for identification of crimes that are reported significantly later and helps determine whether reporting delays do vary across different crime types.

Conclusion : 
- Most crimes are reported either the day of or the day after, with same-day reporting as the clear majority across almost every crime type. This suggests that most incidents are immediately noticed or, because of the severity of the crime, require immediate police involvement. And this can be seen in the data for the more visible and violent crimes, such as assault and burglary. Vehicle-related crimes were the repeating outlier, appearing with a one-day delay for a few crimes, which is likely because in these crimes the theft or damage is only discovered later, often the morning after the incident, which coincides with the pattern seen in my earlier crime-by-hour analysis, with vehicle theft peaking at night. Overall, reporting delays were surprisingly minimal, which is good. This tells us that victims are generally aware of crimes quickly and take action.

In [ ]:
# function to get number of crimes by report delay and crime type
def report_delay(df, top_n=10):
    delay = (
        pd.to_datetime(df['Date Reported']) - 
        pd.to_datetime(df['Date Occurred'])
    ).dt.days  # calculate delay in days

    return (
        df.assign(Report_Delay=delay)  # create new column
        .groupby(['Report_Delay', 'Crime Description'])  # group by delay and crime
        .size()
        .reset_index(name='Count')  # clean DataFrame
        .sort_values(by='Count', ascending=False)
        .head(top_n)
        .reset_index(drop=True)
    )
report_delay(clean_df, 20)

    Report_Delay                                  Crime Description  Count
0              0                           BATTERY - SIMPLE ASSAULT  58092
1              1                                   VEHICLE - STOLEN  52169
2              0     ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT  43714
3              0                  INTIMATE PARTNER - SIMPLE ASSAULT  35645
4              0                                   VEHICLE - STOLEN  33584
5              0  VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...  29285
6              0                                            ROBBERY  26041
7              0                                           BURGLARY  24826
8              1                              BURGLARY FROM VEHICLE  24088
9              0                 THEFT PLAIN - PETTY ($950 & UNDER)  18321
10             0                              BURGLARY FROM VEHICLE  17590
11             0           SHOPLIFTING - PETTY THEFT ($950 & UNDER)  16586
12             1  VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...  15240
13             0                                        TRESPASSING  14914
14             1                                           BURGLARY  14791
15             0           VANDALISM - MISDEAMEANOR ($399 OR UNDER)  14346
16             1    THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER)  14106
17             0             CRIMINAL THREATS - NO WEAPON DISPLAYED  13238
18             0                                  THEFT OF IDENTITY  12683
19             0                                    BRANDISH WEAPON  11952

In [195]:
clean_df

,DR_NO,Date Reported,Date Occurred,Time Occurred,AREA,AREA NAME,UCR Part Classification,Crime Code,Crime Description,Victim Age,...,Weapon Description,Status,Status Desc,Crime Code 1,Crime Code 2,Crime Code 3,Crime Code 4,LOCATION,LAT,LON
0,211507896,2021-04-11,2020-11-07,08:45:00,15,N Hollywood,2,354,THEFT OF IDENTITY,31.0,...,NaN,IC,Invest Cont,354.0,NaN,NaN,NaN,7800 BEEMAN AV,34.2124,-118.4092
1,201516622,2020-10-21,2020-10-18,18:45:00,15,N Hollywood,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",32.0,...,KNIFE WITH BLADE 6INCHES OR LESS,IC,Invest Cont,230.0,NaN,NaN,NaN,ATOLL AV,34.1993,-118.4203
2,240913563,2024-12-10,2020-10-30,12:40:00,9,Van Nuys,2,354,THEFT OF IDENTITY,30.0,...,NaN,IC,Invest Cont,354.0,NaN,NaN,NaN,14600 SYLVAN ST,34.1847,-118.4509
3,210704711,2020-12-24,2020-12-24,13:10:00,7,Wilshire,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,47.0,...,NaN,IC,Invest Cont,331.0,NaN,NaN,NaN,6000 COMEY AV,34.0339,-118.3747
4,201418201,2020-10-03,2020-09-29,18:30:00,14,Pacific,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),63.0,...,NaN,IC,Invest Cont,420.0,NaN,NaN,NaN,4700 LA VILLA MARINA,33.9813,-118.4350
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1004889,240710284,2024-07-24,2024-07-23,14:00:00,7,Wilshire,1,510,VEHICLE - STOLEN,NaN,...,NaN,IC,Invest Cont,510.0,NaN,NaN,NaN,4000 W 23RD ST,34.0362,-118.3284
1004890,240104953,2024-01-15,2024-01-15,01:00:00,1,Central,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),NaN,...,UNKNOWN WEAPON/OTHER WEAPON,IC,Invest Cont,745.0,NaN,NaN,NaN,1300 W SUNSET BL,34.0685,-118.2460
1004891,240410786,2024-10-14,2024-10-11,23:30:00,4,Hollenbeck,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",29.0,...,NaN,IC,Invest Cont,341.0,NaN,NaN,NaN,1700 ALBION ST,34.0675,-118.2240
1004892,240309674,2024-04-24,2024-04-24,15:00:00,3,Southwest,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",70.0,...,STICK,IC,Invest Cont,230.0,NaN,NaN,NaN,FLOWER ST,34.0215,-118.2868
1004893,240910892,2024-08-13,2024-08-12,23:00:00,9,Van Nuys,1,510,VEHICLE - STOLEN,NaN,...,NaN,IC,Invest Cont,510.0,NaN,NaN,NaN,6900 VESPER AV,34.1961,-118.4510