In [2]:
import pandas as pd
import pycountry

In [3]:
file_path = "/Users/kamari/Documents/project_info/IHME_GBD_2010_MORTALITY_AGE_SPECIFIC_BY_COUNTRY_1970_2010.csv"
df = pd.read_csv(file_path)
df

,Country Code,Country Name,Year,Age Group,Sex,Number of Deaths,"Death Rate Per 100,000"
0,AFG,Afghanistan,1970,0-6 days,Male,"19,241","318,292.90"
1,AFG,Afghanistan,1970,0-6 days,Female,"12,600","219,544.20"
2,AFG,Afghanistan,1970,0-6 days,Both,"31,840","270,200.70"
3,AFG,Afghanistan,1970,7-27 days,Male,"15,939","92,701.00"
4,AFG,Afghanistan,1970,7-27 days,Female,"11,287","68,594.50"
...,...,...,...,...,...,...,...
58900,ZWE,Zimbabwe,2010,80+ years,Female,"7,606","16,179.40"
58901,ZWE,Zimbabwe,2010,80+ years,Both,"13,305","16,633.80"
58902,ZWE,Zimbabwe,2010,All ages,Male,"82,010","1,320.10"
58903,ZWE,Zimbabwe,2010,All ages,Female,"77,420","1,211.20"
58904,ZWE,Zimbabwe,2010,All ages,Both,"159,430","1,264.90"

This dataset was already pretty clean and well-structured, so there wasn’t much to do beyond basic validation checks. Most of the values were consistent, including country identifiers which were given as either full names or 3-letter ISO-style codes (like AFG, USA).

However, I found some country names that weren’t fully standardized and used more formal or outdated naming (like “Korea, Republic of” or “Swaziland”), so for consistency I relied on the country codes for grouping and analysis and used the names mainly for labeling.

Categorical fields like gender and age groups were already standardized, and I didn’t find any unexpected or inconsistent labels. Each column also kept consistent data types (for example, years as integers and categories as strings), and there were no missing values in the dataset.

Overall, the data was in good shape and only needed minor cleaning before analysis.

In [4]:
def code_to_country(code):
    country = pycountry.countries.get(alpha_3=code)
    return country.name if country else None

df["Country_Name_Clean"] = df["Country Code"].apply(code_to_country)
df

,Country Code,Country Name,Year,Age Group,Sex,Number of Deaths,"Death Rate Per 100,000",Country_Name_Clean
0,AFG,Afghanistan,1970,0-6 days,Male,"19,241","318,292.90",Afghanistan
1,AFG,Afghanistan,1970,0-6 days,Female,"12,600","219,544.20",Afghanistan
2,AFG,Afghanistan,1970,0-6 days,Both,"31,840","270,200.70",Afghanistan
3,AFG,Afghanistan,1970,7-27 days,Male,"15,939","92,701.00",Afghanistan
4,AFG,Afghanistan,1970,7-27 days,Female,"11,287","68,594.50",Afghanistan
...,...,...,...,...,...,...,...,...
58900,ZWE,Zimbabwe,2010,80+ years,Female,"7,606","16,179.40",Zimbabwe
58901,ZWE,Zimbabwe,2010,80+ years,Both,"13,305","16,633.80",Zimbabwe
58902,ZWE,Zimbabwe,2010,All ages,Male,"82,010","1,320.10",Zimbabwe
58903,ZWE,Zimbabwe,2010,All ages,Female,"77,420","1,211.20",Zimbabwe
58904,ZWE,Zimbabwe,2010,All ages,Both,"159,430","1,264.90",Zimbabwe

In [5]:
sorted(df["Country_Name_Clean"].unique())

['Afghanistan',
 'Albania',
 'Algeria',
 'Andorra',
 'Angola',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bhutan',
 'Bolivia, Plurinational State of',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Brunei Darussalam',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cabo Verde',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo',
 'Congo, The Democratic Republic of the',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czechia',
 "Côte d'Ivoire",
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Eswatini',
 'Ethiopia',
 'Fiji',
 'Finland',
 'France',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Grenada',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran, Islamic Republic of',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 "Korea, Democratic People's Republic of",
 'Korea, Republic of',
 'Kuwait',
 'Kyrgyzstan',
 "Lao People's Democratic Republic",
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Lithuania',
 'Luxembourg',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Micronesia, Federated States of',
 'Moldova, Republic of',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Macedonia',
 'Norway',
 'Oman',
 'Pakistan',
 'Palestine, State of',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Qatar',
 'Romania',
 'Russian Federation',
 'Rwanda',
 'Saint Lucia',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Sweden',
 'Switzerland',
 'Syrian Arab Republic',
 'Taiwan, Province of China',
 'Tajikistan',
 'Tanzania, United Republic of',
 'Thailand',
 'Timor-Leste',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkmenistan',
 'Türkiye',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela, Bolivarian Republic of',
 'Viet Nam',
 'Yemen',
 'Zambia',
 'Zimbabwe']

In [6]:
df_clean = df[['Country Code','Country Name','Country_Name_Clean']]
df_clean

      Country Code Country Name Country_Name_Clean
0              AFG  Afghanistan        Afghanistan
1              AFG  Afghanistan        Afghanistan
2              AFG  Afghanistan        Afghanistan
3              AFG  Afghanistan        Afghanistan
4              AFG  Afghanistan        Afghanistan
...            ...          ...                ...
58900          ZWE     Zimbabwe           Zimbabwe
58901          ZWE     Zimbabwe           Zimbabwe
58902          ZWE     Zimbabwe           Zimbabwe
58903          ZWE     Zimbabwe           Zimbabwe
58904          ZWE     Zimbabwe           Zimbabwe

[58905 rows x 3 columns]

In [7]:
print(df_clean[df_clean["Country_Name_Clean"].isnull()])

Empty DataFrame
Columns: [Country Code, Country Name, Country_Name_Clean]
Index: []

In [8]:
print(df_clean["Country Code"].duplicated().sum())

58718

In [ ]:
the_2000s = df[df['Year'] == 2000]
#df.query("Year == 2010")
the_2000s

,Country Code,Country Name,Year,Age Group,Sex,Number of Deaths,"Death Rate Per 100,000",Country_Name_Clean
189,AFG,Afghanistan,2000,0-6 days,Male,"19,345","168,778.10",Afghanistan
190,AFG,Afghanistan,2000,0-6 days,Female,"13,222","121,860.60",Afghanistan
191,AFG,Afghanistan,2000,0-6 days,Both,"32,567","145,956.20",Afghanistan
192,AFG,Afghanistan,2000,7-27 days,Male,"12,365","36,914.40",Afghanistan
193,AFG,Afghanistan,2000,7-27 days,Female,"9,189","28,855.10",Afghanistan
...,...,...,...,...,...,...,...,...
58837,ZWE,Zimbabwe,2000,80+ years,Female,"4,494","12,189.70",Zimbabwe
58838,ZWE,Zimbabwe,2000,80+ years,Both,"7,703","11,963.90",Zimbabwe
58839,ZWE,Zimbabwe,2000,All ages,Male,"85,971","1,377.70",Zimbabwe
58840,ZWE,Zimbabwe,2000,All ages,Female,"81,924","1,296.00",Zimbabwe
58841,ZWE,Zimbabwe,2000,All ages,Both,"167,896","1,336.60",Zimbabwe

In [ ]:
print(df["Year"].max())

In [12]:
print(df["Year"].max())

2010